import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FunctionComponent } from "react";
import { Header } from "./components";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container flex mx-auto py-8">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
